/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'abed.ali' at '7/26/17 9:16 AM' with Gradle 2.12
 *
 * @author abed.ali, @date 7/26/17 9:16 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
